export const GET_ALL_TIMER_SOUNDS = "GET_ALL_TIMER_SOUNDS";
export const SET_TIMER_SOUND = "SET_TIMER_SOUND";
export const SET_TIMER_VOLUME = "SET_TIMER_VOLUME";
export const SET_TIMER_SILENT_INTERVAL = "SET_TIMER_SILENT_INTERVAL";
