export const SET_INITIAL_STATES_FOR_ALARM_SNOOZE =
    "SET_INITIAL_STATES_FOR_ALARM_SNOOZE";
export const GET_ALL_SNOOZE_INTERVALS = "GET_ALL_SNOOZE_INTERVALS";
export const SET_SNOOZE_INTERVAL = "SET_SNOOZE_INTERVAL";
