export const GET_ALL_TIMERS = "GET_ALL_TIMERS";
export const SET_TIMER = "SET_TIMER";
export const UPDATE_TIMER_TIME = "UPDATE_TIMER_TIME";
export const UPDATE_TIMER_SCHEDULE_FLAG = "UPDATE_TIMER_SCHEDULE_FLAG";
export const UPDATE_TIMER_LABEL = "UPDATE_TIMER_LABEL";
export const DELETE_TIMER = "DELETE_TIMER";
export const SET_TIMER_SOUND = "SET_TIMER_SOUND";
