export const SET_INITIAL_STATES_FOR_ALARM_SILENT =
    "SET_INITIAL_STATES_FOR_ALARM_SILENT";
export const GET_ALL_SILENT_INTERVALS = "GET_ALL_SILENT_INTERVALS";
export const SET_SILENT_INTERVAL = "SET_SILENT_INTERVAL";
