export const SET_INITIAL_STATES_FOR_TIME_ZONE =
    "SET_INITIAL_STATES_FOR_TIME_ZONE";
export const GET_ALL_TIME_ZONES = "GET_ALL_TIME_ZONES";
export const SET_TIME_ZONE = "SET_TIME_ZONE";
export const FETCH_TIME_ZONE_REQUEST = "FETCH_TIME_ZONE_REQUEST";
export const FETCH_TIME_ZONE_SUCCESS = "FETCH_TIME_ZONE_SUCCESS";
export const FETCH_TIME_ZONE_FAILURE = "FETCH_TIME_ZONE_FAILURE";
