import { Html, Head, Main, NextScript } from "next/document";
import type { AppProps } from "next/app";
import { useContext, useEffect } from "react";
import { DataContext } from "@/contexts/DataComponent";
import Layout from "@/components/Layout";

export default function Document() {
    return (
        <>
            <Html lang="en">
                <Head>
                    <title>Clock</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                    <link rel="icon" href="/favicon.ico" />
                    <link
                        rel="preconnect"
                        href="https://fonts.googleapis.com"
                    />
                    <link
                        href="https://fonts.googleapis.com/css2?family=Tektur&display=swap"
                        rel="stylesheet"
                    ></link>
                    <link
                        href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:wght@700&family=Lumanosimo&family=Nabla&family=Noto+Sans+Sundanese:wght@400;700&family=Tektur&display=swap"
                        rel="stylesheet"
                    ></link>
                    <link
                        href="https://fonts.googleapis.com/css2?family=Dai+Banna+SIL&family=Dancing+Script&family=Handjet&family=Kablammo&family=Kalam&family=Lumanosimo&family=Open+Sans&family=Playfair+Display&family=Raleway+Dots&family=Shojumaru&family=Tektur&display=swap"
                        rel="stylesheet"
                    />
                </Head>
                <body>
                    {/* <Layout> */}
                    <Main />
                    {/* </Layout> */}
                    <NextScript />
                </body>
            </Html>
        </>
    );
}
