export const GET_ALL_ALARMS = "GET_ALL_ALARMS";
export const SET_ALARM = "SET_ALARM";
export const UPDATE_ALARM_SCHEDULE_FLAG = "UPDATE_ALARM_SCHEDULE_FLAG"; 
export const UPDATE_ALARM_LABEL = "UPDATE_ALARM_LABEL"; 