export const GET_ALL_ALARMS = "GET_ALL_ALARMS";
export const SET_ALARM = "SET_ALARM";
export const UPDATE_ALARM_TIME = "UPDATE_ALARM_TIME";
export const UPDATE_ALARM_SCHEDULE_FLAG = "UPDATE_ALARM_SCHEDULE_FLAG"; 
export const UPDATE_ALARM_LABEL = "UPDATE_ALARM_LABEL";
export const DELETE_ALARM = "DELETE_ALARM";
export const SET_ALARM_SOUND = "SET_ALARM_SOUND";
export const SET_REPEAT_ALARM = "SET_REPEAT_ALARM";